// training/typescript/src/de/sots/cellarsandcentaurs/application/ui/CreatureCard.tsx
import React from "react";
import type { Creature } from "../../domain/model/Creature";
import { SpeedType } from "@model/SpeedType";

type CreatureCardProps = {
    creature: Creature;
};

export default function CreatureCard({ creature }: CreatureCardProps): React.JSX.Element {
    const walkingSpeed = creature.getSpeeds().get(SpeedType.WALKING);
    return (
        <article className="creature-card">
            <h2>{creature.getId().id}</h2>
            <p>Hit points: {creature.getHitPoints()?.current}</p>
            <p>Walking speed: {walkingSpeed?.getSpeed()}</p>
        </article>
    );
}

// sample-projects/vue/src/de/sots/cellarsandcentaurs/ui/CreatureCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Creature } from '../domain/model/Creature'
import { HitPoints } from '../domain/model/HitPoints'
import { SpeedType } from '../domain/model/SpeedType'

const props = defineProps<{ creature: Creature }>()

const hitPoints = computed(() => props.creature.getHitPoints() ?? HitPoints.init(HitPoints.MAX_HIT_POINTS))
const walkingSpeed = computed(() => props.creature.getSpeeds().get(SpeedType.WALKING)?.getSpeed() ?? 0)
</script>

<template>
  <article class="creature-card">
    <h2>{{ props.creature.getId().id }}</h2>
    <CreatureBadge :label="props.creature.getType()" />
    <p>Hit points: {{ hitPoints.current }} / {{ hitPoints.max }}</p>
    <p>Walking speed: {{ walkingSpeed }}</p>
  </article>
</template>

<style scoped>
.creature-card {
  border: 1px solid #888;
  padding: 0.5rem;
}
</style>
